title: "AWS で試して学ぶ IPv6（BuriKaigi 2026 セッション補足資料）"
summary: "BuriKaigi 2026 1/9 14:20-14:50 Room 203（マス）「AWS で試して学ぶ IPv6」の補足資料です。当日説明する環境の構築方法と利用技術を中心に、説明順序に沿って記載しています。"
topics: ["aws", "vpc", "ipv6"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - 01-top
  - 02-summary-ip
  - 03-summary-vpc-to-create
  - 04-create-ipv4-env
  - 05-review-ipv4
  - 06-modify-server-env-to-dualstck
  - 07-modify-client-env-to-dualstck
  - 08-add-client-env-to-ipv6only-subnet
  - 09-add-server-env-to-ula
  - 10-other-aws-services
  - 11-conclusion
